export let ActionTypes = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_DETAILS_OF_A_SINGLE_PRODUCT: "GET_DETAILS_OF_A_SINGLE_PRODUCT",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
};
